################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
peripherals/CircleBuffer.obj: ../peripherals/CircleBuffer.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/CircleBuffer.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_ADC_cal.obj: ../peripherals/DSP2833x_ADC_cal.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_ADC_cal.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_Adc.obj: ../peripherals/DSP2833x_Adc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_Adc.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_CSMPasswords.obj: ../peripherals/DSP2833x_CSMPasswords.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_CSMPasswords.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_CodeStartBranch.obj: ../peripherals/DSP2833x_CodeStartBranch.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_CodeStartBranch.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_CpuTimers.obj: ../peripherals/DSP2833x_CpuTimers.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_CpuTimers.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_DBGIER.obj: ../peripherals/DSP2833x_DBGIER.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_DBGIER.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_DMA.obj: ../peripherals/DSP2833x_DMA.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_DMA.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_DefaultIsr.obj: ../peripherals/DSP2833x_DefaultIsr.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_DefaultIsr.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_DisInt.obj: ../peripherals/DSP2833x_DisInt.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_DisInt.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_ECan.obj: ../peripherals/DSP2833x_ECan.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_ECan.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_ECap.obj: ../peripherals/DSP2833x_ECap.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_ECap.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_EPwm.obj: ../peripherals/DSP2833x_EPwm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_EPwm.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_EQep.obj: ../peripherals/DSP2833x_EQep.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_EQep.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_GlobalVariableDefs.obj: ../peripherals/DSP2833x_GlobalVariableDefs.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_GlobalVariableDefs.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_Gpio.obj: ../peripherals/DSP2833x_Gpio.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_Gpio.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_I2C.obj: ../peripherals/DSP2833x_I2C.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_I2C.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_Mcbsp.obj: ../peripherals/DSP2833x_Mcbsp.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_Mcbsp.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_MemCopy.obj: ../peripherals/DSP2833x_MemCopy.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_MemCopy.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_PieCtrl.obj: ../peripherals/DSP2833x_PieCtrl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_PieCtrl.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_PieVect.obj: ../peripherals/DSP2833x_PieVect.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_PieVect.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_Sci.obj: ../peripherals/DSP2833x_Sci.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_Sci.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_Spi.obj: ../peripherals/DSP2833x_Spi.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_Spi.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_SysCtrl.obj: ../peripherals/DSP2833x_SysCtrl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_SysCtrl.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_Xintf.obj: ../peripherals/DSP2833x_Xintf.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_Xintf.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/DSP2833x_usDelay.obj: ../peripherals/DSP2833x_usDelay.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/DSP2833x_usDelay.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

peripherals/swfifo.obj: ../peripherals/swfifo.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --include_path="E:/v101/Motion_Card(Independence)/src/Device/myADDA" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionConfig/AxisSet" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myLED" --include_path="E:/v101/Motion_Card(Independence)/src/Control/Kernel" --include_path="E:/v101/Motion_Card(Independence)/src/Control/MotionMode" --include_path="E:/v101/Motion_Card(Independence)/src/Device" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --include_path="E:/v101/Motion_Card(Independence)/header/peripheral" --include_path="E:/v101/Motion_Card(Independence)/header/lib" --include_path="E:/v101/Motion_Card(Independence)/header/user" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myPeripherals" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myIsr" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myFlash" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myEXIO" --include_path="E:/v101/Motion_Card(Independence)/src/Device/myMotors" --include_path="E:/v101/Motion_Card(Independence)/src/Config" --include_path="E:/v101/Motion_Card(Independence)/src/Control" --include_path="E:/v101/Motion_Card(Independence)/src/Task" --include_path="E:/v101/Motion_Card(Independence)/src/Kernal" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/arm-dsp" --include_path="E:/v101/Motion_Card(Independence)/src/Communication/dsp-arm" --advice:performance=all --define=CHECK -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="peripherals/swfifo.d_raw" --obj_directory="peripherals" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


